name: 'Example configuration deploy'
type: profile
description: 'Use configuration from another Drupal site to install a Drupal instance. Suitable for advanced users.'
version: VERSION
core: 8.x
dependencies:
  - node
  - history
  - block
  - breakpoint
  - ckeditor
  - color
  - config
  - comment
  - contextual
  - contact
  - menu_link_content
  - datetime
  - block_content
  - quickedit
  - editor
  - help
  - image
  - menu_ui
  - options
  - path
  - page_cache
  - dynamic_page_cache
  - taxonomy
  - dblog
  - search
  - shortcut
  - toolbar
  - field_ui
  - file
  - rdf
  - views
  - views_ui
  - tour
  - automated_cron
themes:
  - bartik
  - seven
